name: ALF Execute
on:
  workflow_dispatch:
    inputs:   
      SwagCloud_Url:
        type: choice
        description: 'SwagCloud Url'
        options: 
        - https://ipaaspreprodaws.mycloud-us-west-2.softwareag-preprod.cloud/site/index.html#/        
        default: check
        required: true
      SwagCloud_User:
        type: string
        description: 'SwagCloud User'      
        default: mftuser
        required: true
      SwagCloud_Pass: 
        description: 'SwagCloud Password'
        default: ${{ env.super_secret }}
        required: true
      mftCloud_Url:
        type: choice
        description: 'MftCloud Url'
        options: 
        - https://ipaaspreprodaws.mft-aw-us.webmethods-preprod.io/mft/
        default: check
        required: true
      mftCloud_User:
        type: string
        description: 'MftCloud User'      
        default: mftuser
        required: true
      mftCloud_Pass:
        type: string
        description: 'MftCloud Password'
        default: ${{ env.super_secret }}
        required: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:    
      - name: Start ALF
        run: |
          ant -f Codebase/alf-tools/startALF.xml "start.logmonitor.agent"
          ant -f Codebase/job-targets_Docker.xml "start-ALF-Web"
        env: # Or as an environment variable
          super_secret: ${{ secrets.IPAASPREPRODAWS_PASS }}
