name: ALF Execute
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:    
      - name: Start ALF
        run: |
          ant -f Codebase/alf-tools/startALF.xml "start.logmonitor.agent"
          ant -f Codebase/job-targets_Docker.xml "start-ALF-Web" -Dasset.path.to.execute=TCID233805 -Dprediction.engine.action.version=trunk
