name: ALF Report
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:    
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
         name: JEST Tests            # Name of the check run which will be created
         path: Codebase/alf-tools/reports/resources/junit-report.xml    # Path to test results
         reporter: jest-junit        # Format of test results
     # - name: HTML Preview
     #   id: html_preview
     #   uses: pavi2410/html-preview-action@v2
     #   with:
     #     html_file: 'C:/HudsonRoot/MFT_SUITE/playwright/playwright/Codebase/alf-tools/reports/index.html'

