name: ALF Report
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:  
      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: selenium-html-report
          path: C:/Git_Runner_Workspace/playwright/playwright/Codebase/alf-tools/reports/
  publish:
      needs: test
      runs-on: self-hosted
      steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.Git_Push_Token }}
          #publish_dir: C:/Git_Runner_Workspace/playwright/playwright/Codebase/alf-tools/reports/
          publish_dir: docs/_site
          publish_branch: gh-pages
