name: ALF Report
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:  
      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: selenium-html-report
          path: C:/Git_Runner_Workspace/playwright/playwright/Codebase/alf-tools/reports/
