name: MFT BVT Tests
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
      - name: Checkout MFT
        uses: actions/checkout@v4
        with:
          repository: https://github.webmethods.io/AIM/mft
          token: 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
          
