name: MFT BVT Tests
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
      - name: Checkout MFT
        uses: actions/checkout@v4
        with:
          repository: AIM/mft
          token: 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
          github-server-url: https://github.webmethods.io
          sparse-checkout: |
            job_targets
            junit
            installer
            MFTRestAPITest
          path: MFT
      - name: Checkout MBT
        uses: actions/checkout@v4
        with:
          repository: C2E/CNL_Releases
          token: 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
          github-server-url: https://github.webmethods.io/
          path: MBT
          
