name: MFT BVT Tests
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
      - name: Checkout MFT
        uses: actions/checkout@v4
        with:
          repository: AIM/mft
          token: $GIT_TOKEN
          github-server-url: https://github.webmethods.io
          #sparse-checkout: job_targets
          path: MFT
      - name: Checkout MBT
        uses: actions/checkout@v4
        with:
          repository: C2E/CNL_Releases
          token: $GIT_TOKEN
          github-server-url: https://github.webmethods.io/
          path: Codebase/alf-tools
      - name: Checkout Reusable Targets
        uses: actions/checkout@v4
        with:
          repository: SAG/siqa-common-reusable-ant-targets
          token: $GIT_TOKEN
          github-server-url: https://github.webmethods.io/
          sparse-checkout: reusable-ant-targets
          path: reusable-ant-targets
      - name: Copy resource
        run:  |
          cp -R MFT/test-automation/job_targets/* CodeBase/. 
          cp -R reusable-ant-targets/reusable-ant-targets CodeBase/reusable-ant-targets
