name: wMio.MFT_ALF_BVT_Tests
env: 
  mftCloud_Pass: ${{ secrets.CSCAWSUS_PASS }}
  SwagCloud_Pass: ${{ secrets.CSCAWSUS_PASS }}
  TenantName: ${{ github.event.inputs.TenantName }}
on:
  workflow_dispatch:
    inputs:   
      SwagCloud_Url:
        type: choice
        description: 'SwagCloud Url'
        options: 
        - https://cscawsus.mycloud-us-west-2.softwareag.cloud/site/index.html        
        default: check
        required: true
      SwagCloud_User:
        type: string
        description: 'SwagCloud User'      
        default: mftuser
        required: true
      mftCloud_Url:
        type: choice
        description: 'MftCloud Url'
        options: 
        - https://cscawsus.mft-aw-us.webmethods.io/mft/
        default: check
        required: true
      mftCloud_User:
        type: string
        description: 'MftCloud User'      
        default: mftuser
        required: true
      TenantName:
        type: string
        description: 'Tenant Name'      
        default: cscawsus
        required: true
jobs:
  Checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout MFT
        uses: actions/checkout@v4
        with:
          repository: AIM/mft
          ref: develop
          token: ${{ secrets.GIT_TOKEN }}
          github-server-url: https://github.webmethods.io
          sparse-checkout: |
            job_targets
          path: MFT
      - name: Checkout MBT
        uses: actions/checkout@v4
        with:
          repository: C2E/CNL_Releases
          token: ${{ secrets.GIT_TOKEN }}
          github-server-url: https://github.webmethods.io/
          path: MFT_SUITE/alf-tools
      - name: Checkout Reusable Targets
        uses: actions/checkout@v4
        with:
          repository: SAG/siqa-common-reusable-ant-targets
          token: ${{ secrets.GIT_TOKEN }}
          github-server-url: https://github.webmethods.io/
          sparse-checkout: reusable-ant-targets
          path: reusable-ant-targets
      - name: Copy resource
        run:  |
          #rm -rf MFT_SUITE/*
          cp -R MFT/test-automation/job_targets/* MFT_SUITE/    
          cp -R reusable-ant-targets/reusable-ant-targets MFT_SUITE/reusable-ant-targets
          #Copy-Item -Path "MFT/test-automation/job_targets/*" -Destination "MFT_SUITE/" -Recurse -Force
          #Copy-Item -Path reusable-ant-targets/reusable-ant-targets -Destination "MFT_SUITE/reusable-ant-targets" -Recurse -Force
  Execution:
    runs-on: self-hosted
    needs: Checkout
    steps:    
      - name: Start ALF
        run: |           
          ant -f MFT_SUITE/wmio-MFT-targets.xml "updateCloudServerURLsToCurlCommands" -DTenantName=${{ github.event.inputs.TenantName }}
          ant -f MFT_SUITE/wmio-MFT-targets.xml "start-ALF-Web" -DmftCloud_Url=${{ github.event.inputs.mftCloud_Url }} -DSwagCloud_Url=${{ github.event.inputs.SwagCloud_Url }} -DSwagCloud_Pass=${{ secrets.CSCAWSUS_PASS }} -DmftCloud_Pass=${{ secrets.CSCAWSUS_PASS }} -DSwagCloud_User=${{ github.event.inputs.SwagCloud_User }} -DmftCloud_User=${{ github.event.inputs.mftCloud_User }}
  UploadReport:
    runs-on: self-hosted
    needs: Execution
    steps:  
      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: selenium-html-report
          path: MFT_SUITE/alf-tools/reports/
  publishReport:
      needs: UploadReport
      runs-on: self-hosted
      steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.Git_Push_Token }}
          publish_dir: MFT_SUITE/alf-tools/reports/
          publish_branch: gh-pages
